### ISSUE TITLE
Metric appears to be ignored in server mode

### ISSUE THREAD

**Issue by knobotz** [augerai/a2ml#141]
The metric I set in azure.yaml gets ignored and an error message is returned:

```yaml
---
# Azure subscription id
subscription_id: ******

# Name of the DataSet on Azure Cloud
dataset:

# experiment settings unique to Azure, currently just metric used for scoring
experiment:
  # Latest experiment name
  name:
  # Latest experiment run
  run_id:
  ### Metric used to build Model
  metric: accuracy

cluster:
  region: eastus2
  min_nodes: 0a
  max_nodes: 2
  type: STANDARD_D2_V2
  name: a2ml-azure
```

```
[azure]  Found compute target cpucluster ...
[azure]  ConfigException:
        Message: Invalid primary metric specified for classification. Please use one of: ['accuracy', 'precision_score_weighted', 'AUC_weighted', 'norm_macro_recall', 'average_precision_score_weighted']
        InnerException: None
        ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "Invalid primary metric specified for classification. Please use one of: ['accuracy', 'precision_score_weighted', 'AUC_weighted', 'norm_macro_recall', 'average_precision_score_weighted']"
    }
}
SUCCESS: {'azure': {'result': True, 'data': None}}
```

**Expected Behavior**
Metric should be used
